export const SLIDE_MAX_WIDTH = 800;
export const SLIDE_MAX_HEIGHT = 600;
export const LEFT_PANEL_WIDTH = 120;
export const RIGHT_PANEL_WIDTH = 180;
export const SCREEN_MARGIN = 25;
export const SMALL_SCREEN_WIDTH = SLIDE_MAX_WIDTH + LEFT_PANEL_WIDTH + RIGHT_PANEL_WIDTH + 2 * SCREEN_MARGIN;
export const SMALL_SCREEN_HEIGHT = SLIDE_MAX_HEIGHT + 100;
